# Configuration for the copyright headers added to source code files in the repo. Used by the skywalking-eyes tool.
# See dev-docs/docs/developer_guide/workflows/copyright.md for details.
# Also, additional syntax options for this configuration file that are supported by the tool are
# described in the tool's own documentation here: https://github.com/apache/skywalking-eyes.
#
# USAGE
# -------
# To check files:
#    > docker run --rm \
#       -v $(pwd):/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:785bb7f3810572d6912666b4f64bad28e4360799 \
#       -v info \
#       -c .licenserc.yaml \
#       header check
# To fix files automatically:
#    > docker run --rm \
#       -v $(pwd):/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:785bb7f3810572d6912666b4f64bad28e4360799 \
#       -v info \
#       -c .licenserc.yaml \
#       header fix
#
header:
  license:
    spdx-id: N/A
    copyright-owner: DataRobot, Inc.
    content: |-

      Copyright 2023 DataRobot, Inc. and its affiliates.

      All rights reserved.

      DataRobot, Inc.

      This is proprietary source code of DataRobot, Inc. and its
      affiliates.

      Released under the terms of DataRobot Tool and Utility Agreement.

  paths:
    - '**/*.py'
    # - You can temporarily list files below which will be checked when running the tool locally.
    # - 'new-file01.py'

  paths-ignore:
    # these files/directories should not be analyzed
    #
    - 'build/'
    - '__init__.py'

  comment: on-failure
