name: "Release PyPI"

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish-to-test-pypi:
    name: Upload release to PyPI Test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/datarobotx-idp
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/simple/
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
  # publish-to-pypi:
  #   name: Upload release to PyPI
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/datarobotx-idp
  #   steps:
  #     # retrieve your distributions here
  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.PYPI_PASSWORD }}
